language: ruby
sudo: false
cache: bundler
rvm:
  - 2.3.1
  - 2.2.2
script: bundle exec rspec
before_install:
  - gem update --system
  - gem update bundler
services:
  - redis-server
notifications:
  email: false
